# Use a Node.js image as the base for your pipeline
image: node:14

# Define your pipelines
pipelines:
  branches:
    # Pipeline for the main branch (production environment)
    main:
      - step:
          name: Deploy to Production
          script:
            - echo "Deploying to production environment..."

    # Pipeline for the dev branch (development environment)
    dev:
      - step:
          name: Check Code Quality
          script:
            # Install dependencies needed for code quality checks
            - npm install --global eslint

            # Run code quality checks for HTML files using eslint-plugin-html
            - eslint --plugin html --ext .html .
            
      - step:
          name: Optimize JS and CSS
          script:
            # Minify JavaScript and CSS files
            - npm install
            - npm run optimize
  