# Use a Node.js image as the base for your pipeline
image: node:14

# Define your pipelines
pipelines:
  branches:
    # Pipeline for the main branch (production environment)
    main:
      - step:
          name: Optimize and Deploy to Production
          script:
            - npm install
            - npm run pre-deploy
            - npm run deploy
            - echo "Deploying to production environment..."

    # Pipeline for the dev branch (development environment)
    dev:
      - step:
          name: Check Code Quality (JavaScript)
          script:
            # Install dependencies needed for HTML and JavaScript code quality checks
            - npm install --global eslint

            # Run ESLint for JavaScript files
            - eslint . --ext .js --ignore-pattern '*.min.js'

            
      - step:
          name: Optimize JS and CSS
          script:
            # Minify JavaScript and CSS files
            - npm install
            - npm run optimize